"""add default_unit to ingredients

Revision ID: a1b5c6bd2a94
Revises: a795fc92c6e1
Create Date: 2026-03-21 21:53:37.289164

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1b5c6bd2a94'
down_revision = 'a795fc92c6e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ingredients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('default_unit', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ingredients', schema=None) as batch_op:
        batch_op.drop_column('default_unit')

    # ### end Alembic commands ###
