"""Add active status to shopping list

Revision ID: a795fc92c6e1
Revises: 
Create Date: 2024-12-07 00:22:18.529756

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a795fc92c6e1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # Use raw SQL to avoid Alembic batch CircularDependencyError on SQLite.
    # The type-only alter_column calls are no-ops in SQLite and are skipped.
    conn = op.get_bind()
    existing = {row[1] for row in conn.execute(sa.text("PRAGMA table_info(shopping_list)"))}
    if 'is_active' not in existing:
        conn.execute(sa.text("ALTER TABLE shopping_list ADD COLUMN is_active BOOLEAN NOT NULL DEFAULT 1"))
    if 'created_at' not in existing:
        conn.execute(sa.text("ALTER TABLE shopping_list ADD COLUMN created_at DATETIME DEFAULT CURRENT_TIMESTAMP"))
    if 'bought_at' not in existing:
        conn.execute(sa.text("ALTER TABLE shopping_list ADD COLUMN bought_at DATETIME"))


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shopping_list', schema=None) as batch_op:
        batch_op.alter_column('servings',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
        batch_op.drop_column('bought_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('is_active')

    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.alter_column('category',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('recipe_ingredients', schema=None) as batch_op:
        batch_op.alter_column('unit',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('amount',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=False)

    with op.batch_alter_table('ingredients', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    op.create_table('_alembic_tmp_ingredients',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###
