"""add is_staple to ingredients

Revision ID: ce3fe4224f99
Revises: a7d64f91f899
Create Date: 2026-03-22 20:01:33.021458

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce3fe4224f99'
down_revision = 'a7d64f91f899'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ingredients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_staple', sa.Boolean(), nullable=False, server_default=sa.false()))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ingredients', schema=None) as batch_op:
        batch_op.drop_column('is_staple')

    # ### end Alembic commands ###
